/*
Brendan Rooney
CSC 451 Section 701
Assignment 6
11/14/16, 2016
*/

--1.

Select CustomerID, Name
	From CUSTOMER ORDER BY Name;

--2.

Select * 
	From CUSTOMER
		WHERE STATE LIKE 'IL'
			ORDER BY CUSTOMERID;

--3.

Select Name
	From CUSTOMER
		WHERE NAME LIKE '%Furniture%';

--4. 

Select NAME, CITY, STATE
	From CUSTOMER
		WHERE STATE LIKE 'CA' OR STATE LIKE 'FL';

--5. 

Select Distinct STATE
	From CUSTOMER
		ORDER BY STATE;

--6.

SELECT DESCRIPTION, PRICE, FINISH
	FROM PRODUCT
		ORDER BY DESCRIPTION, PRICE DESC;

--7.

SELECT ORDERDATE, COUNT(*)
	FROM ORDERTABLE
  		GROUP BY ORDERDATE
			ORDER BY ORDERDATE;

--8.

SELECT ORDERID, SUM(QUANTITY)
	FROM ORDERLINE
  GROUP BY ORDERID
  ORDER BY SUM(QUANTITY) DESC;

--9.

SELECT NAME, STATE, ORDERID
	FROM CUSTOMER INNER JOIN ORDERTABLE ON ORDERTABLE.CUSTOMERID = CUSTOMER.CUSTOMERID
  		ORDER BY ORDERTABLE.ORDERID;

--10.  

SELECT PRODUCT.PRODUCTID, COUNT(ORDERLINE.PRODUCTID)
  FROM PRODUCT LEFT OUTER JOIN ORDERLINE ON PRODUCT.PRODUCTID = ORDERLINE.PRODUCTID
  GROUP BY PRODUCT.PRODUCTID
  ORDER BY PRODUCT.PRODUCTID;




